import turtle
tina = turtle.Turtle()
tina.shape('turtle')

#Vẽ mặt
tina.penup()
tina.goto(0,0)
tina.begin_fill()
tina.color('yellow')
tina.pendown()
tina.circle(130)
tina.end_fill()

#Vẽ viền mắt trái màu xám
tina.penup()
tina.goto(-50,150)
tina.color('gray')
tina.begin_fill()
tina.pendown()
tina.circle(40)
tina.end_fill()

#Vẽ mắt trái màu trắng
tina.penup()
tina.goto(-50,160)
tina.color('white')
tina.begin_fill()
tina.pendown()
tina.circle(30)
tina.end_fill()

#Vẽ mắt trái màu đen
tina.penup()
tina.goto(-50,170)
tina.color('black')
tina.begin_fill()
tina.pendown()
tina.circle(10)
tina.end_fill()

#Vẽ viền mắt phải màu xám
tina.penup()
tina.goto(50,150)
tina.color('gray')
tina.begin_fill()
tina.pendown()
tina.circle(40)
tina.end_fill()

#Vẽ mắt phải màu trắng
tina.penup()
tina.goto(50,160)
tina.color('white')
tina.begin_fill()
tina.pendown()
tina.circle(30)
tina.end_fill()

#Vẽ mắt phải màu đen
tina.penup()
tina.goto(50,170)
tina.color('black')
tina.begin_fill()
tina.pendown()
tina.circle(10)
tina.end_fill()
"""
tina.color('white')
tina.goto(0,0)
tina.begin_fill()
tina.pendown()
tina.circle(20)
tina.penup()
tina.end_fill()
tina.begin_fill()
tina.color('black')
tina.pendown()
tina.circle(10)
tina.penup()
tina.end_fill()
tina.forward(60)
tina.right(45)
tina.begin_fill()
tina.color('white')
tina.pendown()
tina.circle(30)
tina.penup()
tina.end_fill()
tina.begin_fill()
tina.color('black')
tina.pendown()
tina.circle(10)
tina.penup()
tina.end_fill()
tina.right(90)
tina.forward(90)
tina.begin_fill()
tina.color('maroon')
tina.pendown()
tina.circle(40)
tina.penup()
tina.end_fill()
tina.goto(25,-25)
"""
