"""
    pip install pygame
"""
import pygame
# GAME LOOP
running = True
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT: # generated by clicking close button
            running = False
    # Lấy dữ liệu từ người chơi
    # Cập nhật thông số
    # Vẽ các đối tượng ra màn hình

pygame.quit()